/* eslint-disable */
// AUTO-GENERATED by scripts/build-media.mjs — do not edit by hand.
export interface MediaAsset {
  id: string
  src: string
  width: number
  height: number
  ratio: number
  bytes: number
  lqip: string
  color: string
}
export const AVATARS: string[] = [
  "/media/avatars/a1.webp",
  "/media/avatars/a2.webp",
  "/media/avatars/a3.webp",
  "/media/avatars/a4.webp",
  "/media/avatars/a5.webp",
  "/media/avatars/a6.webp",
  "/media/avatars/a7.webp",
  "/media/avatars/a8.webp",
  "/media/avatars/a9.webp",
  "/media/avatars/b1.webp",
  "/media/avatars/b2.webp",
  "/media/avatars/b3.webp",
  "/media/avatars/b4.webp",
  "/media/avatars/b5.webp",
  "/media/avatars/b6.webp",
  "/media/avatars/b7.webp",
  "/media/avatars/b8.webp",
  "/media/avatars/b9.webp"
]
export const POST_MEDIA: MediaAsset[] = [
  {
    "id": "p1",
    "src": "/media/posts/p1.webp",
    "width": 1080,
    "height": 1350,
    "ratio": 0.8,
    "bytes": 65934,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAACwBACdASoUABkAPvVurFGqpiQiqAqpUB6JaACsHX+gDiAFAXAdm7VjSSqedIx4APGxpJdxh6B+bFETAgVk/VATjaNBnIP187cb7oCSBHSwm1tbNePTv37xdVTll2+OGDoGokidB7q0Fpiit5H7iycSPZdE/MvRKK93G3o7vt89LeOd5PTJqakTcNOE+2QgAAA=",
    "color": "#766148"
  },
  {
    "id": "p2",
    "src": "/media/posts/p2.webp",
    "width": 1080,
    "height": 1080,
    "ratio": 1,
    "bytes": 92262,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACwBQCdASoUABQAPvVurFGqpiQiqAqpUB6JQBWGXEd9AgAu18f+5rOebddLdfCztPvVCPQY+wAA1kLZy6cOkiaOOoO7jUr3vcP1VeTrz8Ip9cuaZwxboBYWiPK1oeXBXU5vAN2MqBwF4lIMjbTAqqU7LqyudUl4uXpfJFnFnKTG68DiXH22/9rLuB4f1VwA",
    "color": "#968b7f"
  },
  {
    "id": "p3",
    "src": "/media/posts/p3.webp",
    "width": 1080,
    "height": 1350,
    "ratio": 0.8,
    "bytes": 107806,
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBQCdASoUABkAPvVssVCqpaSiqAqpUB6JQBdgAZwFzzlXtdvw50ujbEntJbaViQDpAADhvQBg5k4vnrN+YY/XjyFGjzqYcxkfrAP5dcZzKIqVRUDrJIZ9ugJbmxclg48KW1hKcb1XSy1e2u6aQKc3LKd3uCejOGpSnqohrJp9uVAhAAA=",
    "color": "#7c7470"
  },
  {
    "id": "p4",
    "src": "/media/posts/p4.webp",
    "width": 1080,
    "height": 1080,
    "ratio": 1,
    "bytes": 144768,
    "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAABQBQCdASoUABQAPvVysFMqpqSiqAgBUB6JZgC/atpBI81ggvfgzqFt+de0hU39/U06MQAA/tKOsl72ZfMSWFTiJRPNQYA1Gn0YdtXUDPPqDlRIsd6hcshqEexmAC14cXrapQ82KwfKAfWNgp3MA8d74IzzhVyrLmRzQZjrg3I1nuImiSVwBh0Xp68CeWZXtpkdEvRtz6HciSlY5PT82oXhcCH/qNQAAAA=",
    "color": "#5f453a"
  },
  {
    "id": "p5",
    "src": "/media/posts/p5.webp",
    "width": 1080,
    "height": 1350,
    "ratio": 0.8,
    "bytes": 93674,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAQBQCdASoUABkAPvVsqlAqpiOiqA1RUB6JZACdMzLw2n/AGkzh25ECgFW+xxmVOhykAPi0MGFMU4x+c1rezLKNeEXB/0OmWBU01eR5e6NaXmZC1wXelwfEVHrU45s3Zi1pQK9XZGaD9sjyZ0+iuJSaX8U0qEeAPydPxrnMjOy+bjL/EqHQhNTyNjFGpwgAAAA=",
    "color": "#8b5a48"
  },
  {
    "id": "p6",
    "src": "/media/posts/p6.webp",
    "width": 1080,
    "height": 1080,
    "ratio": 1,
    "bytes": 138178,
    "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoUABQAPvVwsFKqpiSiqAgBUB6JQBdgAeKTYuZn3Bj5G+sqzyBAAP7k40Wd/fhoRnV51P7eeV7SArlqtY56Zv8JRua1H0ej1fA4wmP9UibsN8NoEKQVFgw0X32ZqcRmrbXB7UM5oohKJXolhHvXD0HggbA8HPiE1nuNPO8eU8S6PSfiVrgElgAA",
    "color": "#6b5033"
  },
  {
    "id": "p7",
    "src": "/media/posts/p7.webp",
    "width": 1080,
    "height": 1080,
    "ratio": 1,
    "bytes": 178696,
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwBACdASoUABQAPvVsqlCqpiOiqA1RUB6JZQDLpAvIZdLt3w0gHjLd5FbXamLkBpgA1sr/l4ooG5Mj912yD0r0uPoEU1GtX4uj9Ltr/sDRndAIn1zqFvAHrzAVQsPQHGzU7gAAAAA=",
    "color": "#7b7772"
  },
  {
    "id": "p8",
    "src": "/media/posts/p8.webp",
    "width": 1080,
    "height": 1350,
    "ratio": 0.8,
    "bytes": 129382,
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBQCdASoUABkAPvVurlEqpiQiqAqpUB6JQBWAAiO0gkx2UGHHm6WXBIaQnMr198JgAP7pPFh5v3t1Zb/kVCGZkuqsTbc5s2ueHlmB2EYj5y1U8dtN6mJHhM/WHYhDtfOUA3mL6e2zWOamcIpuoU//pXsiYxxUuq9ViAAA",
    "color": "#355246"
  },
  {
    "id": "art-a1",
    "src": "/media/posts/art-a1.svg",
    "width": 800,
    "height": 1000,
    "ratio": 0.8,
    "bytes": 0,
    "lqip": "",
    "color": "#4c1d95"
  },
  {
    "id": "art-a2",
    "src": "/media/posts/art-a2.svg",
    "width": 800,
    "height": 1000,
    "ratio": 0.8,
    "bytes": 0,
    "lqip": "",
    "color": "#0f172a"
  },
  {
    "id": "art-a3",
    "src": "/media/posts/art-a3.svg",
    "width": 800,
    "height": 1000,
    "ratio": 0.8,
    "bytes": 0,
    "lqip": "",
    "color": "#7c2d12"
  },
  {
    "id": "art-a4",
    "src": "/media/posts/art-a4.svg",
    "width": 800,
    "height": 1000,
    "ratio": 0.8,
    "bytes": 0,
    "lqip": "",
    "color": "#064e3b"
  },
  {
    "id": "art-a5",
    "src": "/media/posts/art-a5.svg",
    "width": 800,
    "height": 1000,
    "ratio": 0.8,
    "bytes": 0,
    "lqip": "",
    "color": "#312e81"
  },
  {
    "id": "art-a6",
    "src": "/media/posts/art-a6.svg",
    "width": 800,
    "height": 1000,
    "ratio": 0.8,
    "bytes": 0,
    "lqip": "",
    "color": "#451a03"
  }
]
